markdown:    rdiscount
pygments:    true

destination: ./_site
server:      true
auto:        true
server_port: 4000
permalink:   date 

paginate:    15

Jan:  31
Feb:  28
Mar:  31
Apr:  30
May:  31
Jun:  30	
Jul:  31
Aug:  31
Sep:  30
Oct:  31
Nov:  30
Dec:  31

analytics :
  provider : google 
  google : 
      tracking_id : 'UA-45805822-1'